### ISSUE TITLE
Is there any simple installation way for users?

### ISSUE THREAD

**Issue by yanirmr** [cisocrgroup/pocoweb#28]
Hi,
I work in a team with non-tech (actually, they tech but non-dev) users and I couldn't find installation wizards or something similar for them. Most of them, by the way, works with Windows and Macs, not Linux so the proposed installation procedure is not really relevant to them either.

Do you have any ideas for me?
thanks.

**Comment by sinairusinek** [comment]
would it be possible perhaps to make pocoweb available on docker?

**Comment by finkf** [comment]
Pocoweb is deployed using docker-compose. I will write up some more detailed installing instructions. For short (docker-compose must be installed and a ssl key pair must be available):
- `$ cp /path/to/cert services/nginx/cert.pem`
- `$ cp /path/to/key services/nginx/key.pem`
- `$ sudo make docker-start`
- All files are installed into the `/srv/pocoweb` directory
- pocoweb is available via `localhost`

**Comment by yanirmr** [comment]
Hi @finkf and thanks for your comment.
Unfortunately, I  failed to use what you wrote to activate PocoWeb.
where is the yaml file for docker-compose?
could you give more information about installing pocoweb?
it will be wonderful.

**Comment by finkf** [comment]
We are on our way to finish the development and documentation of pocoweb to the end of November. If you want to try it out you have to use the documentation of the [Readme.md](https://github.com/cisocrgroup/pocoweb/blob/devel/README.md) in the devel branch of this project. The information on the master branch is slightly outdated.
