### ISSUE TITLE
create project: Timeout (504 nginx)

### ISSUE THREAD

**Issue by jbarth-ubhd** [cisocrgroup/pocoweb#37]
Did get a timeout message when creating a ~350 pages project.

Then did Apache 2.4 `ProxyTimeout=1200`.

Now' I'm getting the error message `Timeout (504 nginx)`;

tried this: 
```diff
diff --git a/services/nginx/nginx.conf b/services/nginx/nginx.conf
index ab5c48f0..6559594b 100644
--- a/services/nginx/nginx.conf
+++ b/services/nginx/nginx.conf
@@ -16,7 +16,7 @@ http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
-       keepalive_timeout 65;
+       keepalive_timeout 1200;
        types_hash_max_size 2048;
        server_tokens off;
```

but this doesn't help.

**Comment by finkf** [comment]
Sorry, but I was preoccupied with something else and missed your issues.  Does this project contain large non-binarized image files?  You could try to use binarized page images to reduce the size of the archive.

**Comment by jbarth-ubhd** [comment]
The 375 images (41 MB total) were all `Compression Scheme: CCITT Group 4` (black-and-white)

**Comment by finkf** [comment]
If I upload a large file, I can reproduce your error, but in my case the project is still uploaded.  It seems to be a problem with nginx's `proxy_timeout` settings.  I am investigating this.

**Comment by finkf** [comment]
Try these settings (in `services/nginx/nginx.conf`) to increase the proxy timeout settings of nginx:
```
http{
   ...
   proxy_read_timeout 300;
   proxy_connect_timeout 300;
   proxy_send_timeout 300;
   ...
}
```
