### ISSUE TITLE
make and mysql errors

### ISSUE THREAD

**Issue by jpb-badw** [cisocrgroup/pocoweb#41]
When running the make -j command, following errors were received:
`~/Desktop/pocoweb$ make -j`
[rest/src/core/Archiver.o]
[rest/src/core/App.o]
[rest/src/core/Book.o]
[rest/src/core/BookBuilder.o]
[rest/src/core/BookConstructor.o]
[rest/src/core/BookDirectoryBuilder.o]
g++: error: : No such file or directory
g++: error: : No such file or directory
g++: error: : No such file or directory
[rest/src/core/BookFixer.o]
make: *** [make/config.make:60: rest/src/core/Archiver.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [make/config.make:60: rest/src/core/App.o] Error 1
make: *** [make/config.make:60: rest/src/core/BookBuilder.o] Error 1
g++: error: : No such file or directory
g++: error: : No such file or directory
g++: error: : No such file or directory
make: *** [make/config.make:60: rest/src/core/Book.o] Error 1
make: *** [make/config.make:60: rest/src/core/BookConstructor.o] Error 1
make: *** [make/config.make:60: rest/src/core/BookDirectoryBuilder.o] Error 1
g++: error: : No such file or directory
make: *** [make/config.make:60: rest/src/core/BookFixer.o] Error 1

Also when running mysql:
`~/Desktop/pocoweb$ mysql -h dbhost -u dbuser -p < db/tables.sql` \
Enter password:
ERROR 2005 (HY000): Unknown MySQL server host 'dbhost' (11)

**Comment by finkf** [comment]
`dbhost` stands for the actual database host (see the end of the README for more information). 

The build process is quite fragile.  Take a look at the [Dockerfile](Dockerfile) to see how pocoweb can be built.  You should not build pocoweb outside docker and docker-compose.

**Comment by jpb-badw** [comment]
Thanks @finkf for the answer.
After making some adjustments mysql -h 172.18.0.6 pocoweb -p pocoweb prompts _MariaDB Monitor_
From here, how do I access the actual web interface? 
In the past, I have been able to access the interface through [pocoweb.cis.lmu.de](pocoweb.cis.lmu.de])

**Comment by finkf** [comment]
If you use docker, you should be able to access the website via https:/localhost and the api via https:/localhost/rest ...
