### ISSUE TITLE
Bugged Lines

### ISSUE THREAD

**Issue by jpb-badw** [cisocrgroup/pocoweb#42]
It appears that some lines are crambled until one clicks on them. What is the reason for this problem?
![image](https://user-images.githubusercontent.com/73533526/101785670-514bef80-3afd-11eb-8c59-f17a8642064a.png)

**Comment by finkf** [comment]
That seems to be a problem with the display algorithm.  In short we try to align the tokens with the input images. If the line snippets are to small (in the image it seems that the images are missing) the algorithm break down and produces overlaps. You can use the `display settings` tabs in the left menu bar and increase the line hight.
