### ISSUE TITLE
Correction Display: mismatch between image size and OCR'ed token positions 

### ISSUE THREAD

**Issue by cboulanger** [cisocrgroup/pocoweb#49]
I have the problem that in my workflow, the tool extracting images from the PDF of high enough resolution creates images that are of a different size than what the Abbyy FineReader XML document describes, which results in a broken correction display (Lines are out of sync between OCR text and image). Is there a setting in PocoWeb which could be adjusted to adapt the display?

**Comment by finkf** [comment]
Currently there is no such setting.  The lines are fixed, because on the server side we cut the images into line snippets on project import.

**Comment by cboulanger** [comment]
Is a "scale factor" something you might find sensible as a feature request and would consider to implement at all? Otherwise it might make sense to put in a size check in the project import and reject images that do not match the description in the XML.

**Comment by finkf** [comment]
Yes.  I guess that such a scale factor is something worthwhile to implement.

**Comment by finkf** [comment]
Do your Abbyy XML files contain the specific scale factor or does this occur implicit in that the image dimensions do not match the dimensions in the XML files?

**Comment by cboulanger** [comment]
The Abbyy XML file contains, for example, ` <page width="2478" height="3508" resolution="300" originalCoords="1">`. The image file that I get from my image extraction is `page-001.png: PNG image data, 2378 x 3367, 8-bit/color RGBA, non-interlaced` (as per `file page-001.png`) and the particular library doesn't allow me to set the output file size. If it helps I could upload xml and png here.

**Comment by finkf** [comment]
That would help a lot.  Thanks

**Comment by cboulanger** [comment]
![page-001](https://user-images.githubusercontent.com/75390/119990771-077e9500-bfc9-11eb-8c01-5ed7cda2cecd.png)

[page-001.xml.txt](https://github.com/cisocrgroup/pocoweb/files/6561105/page-001.xml.txt)

(I needed to add a `.txt`extension because GitHub doesn't like `.xml`

**Comment by cboulanger** [comment]
The complete project is in my account at https://pocoweb.cis.lmu.de/#projects/5 - I don't know if you have admin access to it.

**Comment by finkf** [comment]
I just deployed a version that automatically calculates and applies a scaling factor to the line snippets.  You have to re-upload your project, though.

**Comment by cboulanger** [comment]
It works, thank you very much!! Closing.
