### ISSUE TITLE
Bigger size of "popups"

### ISSUE THREAD

**Issue by cboulanger** [cisocrgroup/pocoweb#52]
![Bildschirmfoto 2021-05-31 um 13 29 16](https://user-images.githubusercontent.com/75390/120187422-0b9ef280-c215-11eb-9642-9a329a947c68.png)

In popup displays, such as the concordance view in the above screen-shot, the working area is smaller than the text displayed, even though there is enough space available in the browser window, leading to a situation where the text to be corrected has to be moved back and forth with the scroll bars.

Solution: size the popup display with t a fixed margin to the viewport instead of a proportion.

**Comment by cboulanger** [comment]
It might also be the case that the display is the way it is in my case because of https://github.com/cisocrgroup/pocoweb/issues/49

**Comment by tenglmeier** [comment]
I have increased the size of the popup. If it still does not work, please let me know.

**Comment by cboulanger** [comment]
👍  Thank you!
