### ISSUE TITLE
Pocoweb (commit e74a1b048c2…) does not work?

### ISSUE THREAD

**Issue by jbarth-ubhd** [cisocrgroup/pocoweb#56]
OCR+TIFFs: https://digi.ub.uni-heidelberg.de/diglitData/v/rupp4.zip

![grafik](https://user-images.githubusercontent.com/30653779/127861945-0c36b3d7-d326-4138-b74e-26b25bb49e81.png)

**Comment by finkf** [comment]
The first few pages of the project are empty; so no lines are displayed as default. If you skip ahead e.g. to page 15 you will see the line snippets and their according OCR-recognition. I guess that this issue is related to #54 (tif images cannot be displayed).

**Comment by finkf** [comment]
@tenglmeier : maybe we need to handle empty pages in a more obvious way, though.

**Comment by tenglmeier** [comment]
Yes definitely, empty pages are currently not taken into account and lead to errors.

**Comment by tenglmeier** [comment]
The Javascript error should be gone
