### ISSUE TITLE
Move project to other user?

### ISSUE THREAD

**Issue by jbarth-ubhd** [cisocrgroup/pocoweb#61]
It is possible to move a project to an other user?

Even the admin sees his projects only.

The checkbox "... pool ..." is not working in project settings — after logout+login the check is vanished.

The links »Download project pool« and »Download root's projects« are linking to https://pocoweb.cis.lmu.de/rest/pool/global?auth=XXXXXX instead of our local installation.

**Comment by finkf** [comment]
This is by design. Each admin only sees their own projects their projects are completely separated.

**Comment by finkf** [comment]
I have created to separate issues #62 and #63 for the other two issues. Thank you for reporting.
